
server:
  port: 8080
  servlet:
    context-path: /cinema/api

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNER_KEY}

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

storage:
  image-dir: data/image


gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}