#server:
#  port: 8080
#  servlet:
#    context-path: /cinema/api
#
#spring:
#  config:
#    import: optional:file:.env[.properties]
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
##        ddl-auto: create
#    show-sql: true
#
#jwt:
#  signerKey: ${JWT_SIGNER_KEY}
#
#
#springdoc:
#  swagger-ui:
#    path: /swagger
#  api-docs:
#    path: /api-docs
#
##  git log --graph --decorate --oneline --all -15
#
#
#storage:
#  image-dir: data/image
#

server:
  port: 8080
  servlet:
    context-path: /cinema/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_booking_system
    username: root2
    password: 012345678910

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: AgAOx4qyAzSy8CqqI4zuNJgm3vozakUHD8JICWkLh1j6AHcIzDfjXeyz1YkG8Amu

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

storage:
  image-dir: data/image
